### ISSUE TITLE
incorrect game list fetch url?

### ISSUE THREAD

**Issue by buck2202** [rallion/depressurizer#8]
depressurizer insists that my profile is not public even though it actually is. I'm able to get an xml list of my library by manually going to a url like
http://steamcommunity/profiles/xxx/games/?tab=all&xml=1

but not the url fetched by depressurizer without a trailing slash on "games"
http://steamcommunity/profiles/xxx/games?tab=all&xml=1
this one falls back the profile "home page"

**Comment by rallion** [comment]
Hmm, I can't reproduce this. It works just as well with or without the slash, through the program and through a browser. I'm not saying you're wrong, just that I can't figure out why this is happening to you and not to me.

For my own account, both of these work fine for me:

http://steamcommunity.com/profiles/76561197989742194/games?tab=all&xml=1
http://steamcommunity.com/profiles/76561197989742194/games/?tab=all&xml=1

Could you see if they both work for you?

If adding a trailing slash fixes a problem for anybody, I'll add it, but I'm just not sure that's the problem here.

**Comment by buck2202** [comment]
hm..never mind, I guess. It was definitely not working without the trailing slash when I initially posted, but it is now. I have no idea why. Maybe it just took a while for the change of my game list to 'public' to totally propagate through steam's servers?
